Ethan subsystem
FRC1257/robotics-training pull request #12
Opened 2020-03-29 07:28 UTC by EthanMuchnik

Proofread plz

2020-03-30 00:52 UTC, rcya1 requested changes
Overall, I dislike the style where you just throw a ton of code at people and then explain what it does. I generally find this really uneffective and hard to follow. I prefer to instead do an actual process of what someone programming a subsystem might choose to do. For instance, going through
1. Putting in and setting up the appropriate motor controllers
2. Defining the correct states
3. Creating the states and adding them to the enum and the update() function
4. Creating the functions to go into those states
Look at my examples from stuff such as outputting values to shuffleboard or the PID one for examples

2020-03-30 00:52 UTC, Ryan10145 commented on frc/1. Basics/5a. First Subsystem (Roller Intake).md
> +**Now for the line by line review:**
For this part the line by line is fine but when you actually get into programming a subsystem which people should be understanding more deeply so they can do it for their own subsystems, imo this style is bad

2020-03-30 00:54 UTC, Ryan10145 commented
FYI to anyone looking, do NOT merge this yet (I'm looking at you Matt) because we still need to work on the other sections (this should be a draft PR but oh well).

2020-04-10 17:45 UTC, matth101 commented
Nice job overall.

2020-04-10 17:45 UTC, merged